### ISSUE TITLE
Entire app falls over when <Link /> is passed a bad param

### ISSUE THREAD

**Issue by mherodev** [Yolk-HQ/next-routes#53]
Right now, when the `<Link />` component is passed `null` instead of an expected string, it throws an error which causes our app to fall over.

I'm tempted to write a wrapping component that checks for bad params and renders an `<a />` with no `href` instead of a `<Link />`, but it seems like that'd be a pretty reasonable default behavior for `<Link />` when passed bad params. 

Perhaps the app could fall over in development, but in production? It's just a bad link, it shouldn't be catastrophic; I'm fine sending a user to a 404 instead.

If it's `null`

```
Uncaught (in promise) TypeError: Expected "id" to be a string
    at Route.toPath
    ...
```

or if it's an empty string

```
Uncaught (in promise) TypeError: Expected "id" to match "[^\/]+?", but got ""
    at Route.toPath (index.js:180)
    at Route.getAs (index.js:275)
    at Route.getUrls (index.js:289)
    at Routes.findAndGetUrls (index.js:123)
    at LinkRoutes (index.js:184)
```

**Comment by elliottsj** [comment]
Thanks for the issue.

I agree that we shouldn't cause a fatal error when the passed parameter type is incorrect. Instead, a warning in the console (like React prop types) would probably be better.

The error originates from [`pathToRegexp.compile()`](https://github.com/pillarjs/path-to-regexp#compile-reverse-path-to-regexp), which raises a TypeError whenever an invalid parameter is passed. This method does not return "partial" paths (e.g. `pathToRegexp.compile('/user/:id')({ id: '' })` raises a TypeError instead of returning `'/user/'`), so we would need to provide a way for the user to specify a default path like `/404` or something.

We also should keep in mind that emitting a warning instead of raising an error would be considered a breaking change, since existing users could be depending on these errors in an error boundary.

**Comment by elliottsj** [comment]
In the meantime, I'd recommend rendering your `<Link />`s within an error boundary if you expect that invalid params will be passed.

**Comment by mherodev** [comment]
Thanks Elliott! We're going to wrap `<Link />` in our own local component that'll try to handle these error states in the mean time.

**Comment by elliottsj** [comment]
This package is obsolete as of Next.js v9, since [dynamic routes are now natively supported](https://nextjs.org/blog/next-9#dynamic-route-segments).
